name: CI
on:
  push: { branches: [main] }
  pull_request:
  merge_group:

env:
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: -Dwarnings
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: full

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      matrix:
        build: [stable, beta, nightly]
        include:
          - build: stable
            os: ubuntu-24.04
            rust: stable
          - build: beta
            os: ubuntu-24.04
            rust: beta
          - build: nightly
            os: ubuntu-24.04
            rust: nightly
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      run: rustup update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
    - name: Build and run tests
      run: cargo test

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      run: rustup update stable && rustup default stable && rustup component add rustfmt
    - run: cargo fmt --check
